### ISSUE TITLE
Battery Information

### ISSUE THREAD

**Issue by fgmccrea** [fesch/CanZE#537] opened 2019-02-21 09:20 UTC
Now that there are a few spare buttons in 'experimental....

Please please make one show total kwh in battery life

(Looking for a good used Zoe, and battery may or may not have seen a lot of use)

**Comment by yoh-there** [comment] 2019-02-21 09:40
Duplicate of #531. Will be available in the next release

**Closed as completed by yoh-there** 2019-02-21 09:40 UTC
Labels: duplicate

**Comment by fgmccrea** [comment] 2019-02-21 09:41
Faster than R110 off the lights!  Thank you
