### ISSUE TITLE
CanZE TMPS IDs: buttons or description interchanged

### ISSUE THREAD

**Issue by SMCinc** [fesch/CanZE#569] opened 2019-09-15 09:43 UTC
Hello, in the german version the decription of the buttons for reading/writing tyre IDs is interchanged;
on bottom left the button 'ID SCHREIBEN' does read the IDs from control unit / bottom right 'ID LESEN' does write IDs to control unit.

I am using CanZE Version 1.41 // Build: 2019.08.05 on Android with CANsee dongle on ZOE Q210

**Comment by yoh-there** [comment] 2019-09-15 16:43
Thanks for reporting. Duplicate of #554 (see posts user Gerd). Fix will be incorporated in the next release.

**Closed as completed by yoh-there** 2019-09-15 16:43 UTC
