### ISSUE TITLE
Tire valve ID's cannot be written...

### ISSUE THREAD

**Issue by AndreasBahrt** [fesch/CanZE#581] opened 2019-11-12 07:49 UTC
... From CanZE v.1.43 (Android 7.1.2).

When write of the TPMS ID's are tried, message **Could not read write valves:-E-ISOTP tx flow error** appears...

Thank you!

![Write Valve ID's not working](https://user-images.githubusercontent.com/57658011/68651907-a7c8b200-0528-11ea-96b8-39eb7e064113.jpg)
![CanZE software version](https://user-images.githubusercontent.com/57658011/68651922-b020ed00-0528-11ea-8bdf-d15e686bb082.png)

**Comment by yoh-there** [comment] 2019-11-12 08:34
Duplicate of #577. Will you please try with the latest update, and report back in that issue? It's possibly a timing issue. Thank you!

(sorry, wrote 554 first)

**Closed as completed by yoh-there** 2019-11-12 08:34 UTC

**Comment by AndreasBahrt** [comment] 2019-11-13 06:06
CanZE is now updated to version 1.46. Please look at the following messages which are revealed in CanZE, when the write button is pressed...
![Udklip](https://user-images.githubusercontent.com/57658011/68737507-f2f3cb00-05e3-11ea-9a23-6ee6a2ac760b.PNG)
![Udklip2](https://user-images.githubusercontent.com/57658011/68737524-fb4c0600-05e3-11ea-856b-a77fc814a7c5.PNG)
![Udklip3](https://user-images.githubusercontent.com/57658011/68737541-07d05e80-05e4-11ea-81c5-04d9731952f4.PNG)

**Comment by AndreasBahrt** [comment] 2019-11-13 06:07
Read does not work either...
![Udklip4](https://user-images.githubusercontent.com/57658011/68737614-3fd7a180-05e4-11ea-9621-0d024f80c5c2.PNG)

**Comment by AndreasBahrt** [comment] 2019-11-13 06:12
... I intend to try another Android device, when I find one...

**Comment by yoh-there** [comment] 2019-11-13 08:27
https://github.com/fesch/CanZE/issues/577
