### ISSUE TITLE
Cell Voltages

### ISSUE THREAD

**Issue by MAlfare** [fesch/CanZE#343] opened 2016-05-30 23:31 UTC
Hi!

During charging I could see a serious difference between cell voltages in BATT VOLTAGES -Voltage heatmap and BATTERY - Cell Voltages (V).

While voltages of all cells in heatmap are over 4 Volts, all voltages in BATTERY - Cell Voltages are at approximately 3.6 Volts.

Where is the difference coming from?
Are there different sources of data?
Is the difference Ri \* Ic (Ri = inner resistance of the cell, Ic = charging current)?

Regards
Manfred

**Comment by fesch** [comment] 2016-05-31 04:59
This is quite strange, as the same CAN messages are being used to obtain both information .... !?

**Comment by yoh-there** [comment] 2016-05-31 07:32
Exactly. @fesch is there any way (and if not, this is a suggestion) to disable pulling the variables from the database and instead only show real time data?

**Comment by yoh-there** [comment] 2016-07-18 10:04
Unable to reproduce. Closing

**Comment by MAlfare** [comment] 2016-07-21 11:20
Hi yoh-there!

I **am** able to reproduce!

You can close whatever you want, it's your party.
But is it good habit, to ignore bugs in that way? 

Have a look at the two screen shots, taken immediately one after the other.

Maybe the values are O.K but the scale is faulty?
![screenshot_2016-07-21-11-38-17](https://cloud.githubusercontent.com/assets/4406655/17021012/4a7c9f9a-4f45-11e6-96f8-bdf816b81516.png)
![screenshot_2016-07-21-11-38-33](https://cloud.githubusercontent.com/assets/4406655/17021013/4a83bd66-4f45-11e6-8ec3-5a0b4c77c546.png)

**Comment by yoh-there** [comment] 2016-07-21 11:53
Double checked against current source. Source (battery.xml) seems right, but I can confirm @MAlfare 's screen print. @fesch could you please have a quick look at the widget code? As I am 99% convinced the heatmap is right (as in: stupid simple, it just prints the value in the proper block)

**Comment by fesch** [comment] 2016-07-28 08:42
Can confirm: got a voltage heatmap with values > 4 but the graph on the battery screen displays them below 4 ....

**Comment by fesch** [comment] 2016-07-28 09:03
Got it! This will be fixed in the next release ...

**Comment by yoh-there** [comment] 2016-07-29 11:05
Great. I would not mind a release. It would fix this, might fix #342 and put the prediction (which was relatively crap in the previous release) in the wild for real user testing ;-) Up to you of course.

**Comment by fesch** [comment] 2016-07-29 11:23
I must admit that I did not yet test the prediction too. Each time I charged the last few days my pad has not right near me ;-)

**Comment by fesch** [comment] 2016-07-29 11:23
But I close this issue now anyway. 
The fix will come with the next release ...

**Closed as completed by fesch** 2016-07-29 11:23 UTC
