### ISSUE TITLE
R240: value for "energy to 100% charged" wrong if battery has low SOC

### ISSUE THREAD

**Issue by Lokverfuehrer** [fesch/CanZE#470] opened 2017-10-21 20:49 UTC
CanZE Version 1.25

With SOC around 5% CanZE shows available energy of 1 kWh and 12,3 kWh till fully charged. It should be around 22,3 kWh. 
At higher SOC CanZE seems to work correctly. 

Screenshot:
![screenshot_20171021-123848](https://user-images.githubusercontent.com/18364992/31855759-ebc409cc-b6b1-11e7-9a3e-ff7b8f1e8598.jpg)

**Comment by yoh-there** [comment] 2017-10-22 10:38
Problem is caused by the re-use of the soc variable for real and user SOC; the calculation is correct for the real soc, but that one should not be used.

**Comment by yoh-there** [comment] 2017-10-22 11:03
Fixed in #2c0918c

**Closed as completed by yoh-there** 2017-10-22 11:03 UTC
Labels: bug
