### ISSUE TITLE
Can not get Canze to work on IOS

### ISSUE THREAD

**Issue by exycutez** [fesch/CanZE#439] opened 2017-02-18 17:04 UTC
Hello,

I just got a wifi obd from china (http://s.aliexpress.com/iIZNjQzi). As i read on the canze website, any v1.5 wifi obd should work, however it just says "connecting to wifi-socket" and it says that forever. I have to quit the app to get the message away. I have been using the static ip and subnet, and default port settings, but still no luck..

Any thoughts? I have now ordered a new kw902 wifi dongle, as i assume ita the dongle?

**Comment by GertjanVB** [comment] 2017-02-18 17:15
The dongle you're indicating is working for me. Did you connect WiFi with the password? You need to do that only once. First time connections seems to take a while. Is the automatic connection slider in "settings" active? Can you see an active WOBD WiFi connection in iOS settings?

**Comment by yoh-there** [comment] 2017-02-18 17:16
Thanks GJ. I would appreciate if someone would write an article for the website on what works for iOS and what not and how, like for the Android version (preferably better ;-) ).

**Comment by GertjanVB** [comment] 2017-02-18 17:19
I will have a try...

**Comment by exycutez** [comment] 2017-02-18 17:22
There was no password to connect to wifi..

This is what i have done:

1. Plug in the dongle (light is blinking some different colors, and then it is showing a solid red led)
2. Connecting to the wifi obd, i recieve ip 192.168.0.0X (from 1-9), and the router ip is 192.168.0.10.. then i set static ip to the same as the regular ip (also tried 192.168.0.123) and subnet to 255.255.255.0.. 
3. When this is done, i hit "try find dongle" and it says it might be the adress 192.168.0.10, so i dont mess around with that in canze.. and i i try, i get error..
4. Trying to connect, and it says "connecting to wifi-socket", longest time i have been waiting on it is 1 hour!

**Comment by GertjanVB** [comment] 2017-02-18 17:30
When no connection with the dongle is made by CanZE, you should get an "unable to connect" message
Which CanZE version are you using, mine is 1.0.15.7
Do you have an active wifi connection in iOS with the dongle, (GBe: Yes, obviously: you get an IP address, sorry.)
1 hour is long enough :-/ Did you drive with the car and CanZE?
Car settings in CanZE ok?
When you start CanZE without a dongle installed, do you get the same freeze or is the message "unable to connect"" shown
What phone are you using 
Does your dongle looks exact like the picture of Ali? Sometimes a different model is shipped.

I'm out of suggestions, but I can tell I had a moment that I wanted to trash the dongle, but all of a sudden it worked. Not a very scientific approach, however. The same for: restart everything, but sometimes it works.

**Comment by exycutez** [comment] 2017-02-18 19:13
If i try putting "192.168.0.10" as static ip on wifi settings on iphone, i get unable to connect bla bla.. if i changw ip field in canze i get unable to connect.. 
Newest canze version (1.0.15.7), i did not drive the car, the car was charging and closed for most of the time, however, i have tried to have it connected while driving for approx 15 min, is that long enough? Car settings is r240, have not changed the socket read timeout.. get unable to connect when no dongle in car. It dowsnt freeze with the dongle, it just load forever with the attempting to connect to wifi socket..

Phone is iphone 7 plus, same dongle as on ali.

**Comment by exycutez** [comment] 2017-02-18 19:19
By the way, i just saw that the wifi symbol on my screen up left corner is missing when i enter the static ip..

However, it says im connected to the dongle, and i am getting an ip from it, if i trust canze when hitting "try find dongle"

**Comment by GertjanVB** [comment] 2017-02-18 19:43
There is no wifi icon in the top left during connection with the dongle, that's ok
CanZE seems to recognize the dongle, but there seems to be no connection and data transfer 
I can't remember the exact procedure for connecting, but as a result there's a wifi WOBD connection 
I was convinced you had to use the password 12345678 to make this connection, which is made outside CanZE in the iOS setting panel.
Tomorrow I will erase my settings and go through the procedure to get connected.

**Comment by exycutez** [comment] 2017-02-18 20:53
It is not passeord protected for me, just plug and connect! Just tried connecting for 35 mins while driving, when stopping the car CsnZE still tried to connect to it!

**Comment by exycutez** [comment] 2017-02-18 20:58
Well, i bought 2 of theese cheap dongles, and found out that it was this (http://s.aliexpress.com/V7FbeyUv) that i have now and that has arrived.. it says "obdii interface" instead of "ELM327" interface!

Could this be the problem?

**Comment by FredLeudon** [comment] 2017-02-18 21:20
CanZE for ios uses a Wifi ODB2 dongle.

It means that there are two connexion to perform. 

First step is to join dongle's wifi network.
In some case, dongle use open wifi network (mine is called wifi-odb2) and in other cases, dongle provides à private wifi network (so You have to know wifi password)
- go to Apple iPhone settings, wifi and join your dongle wifi network.
- if successful, tap the i sign to view ip, subnet and gateway assigned by the dongle's dhcp server. 
- laungh CanZE, go to settings. Enter gateway as dongle's ip address
- all wifi dongle I tested uses port 35000
- slide to connexion page and tap connect, normaly, it works fine.

To check Your Wifi dongle, You can install this software (EOBD Facile - OBD2 Diagnostic Automobile par OUTILS OBD FACILE SARL
https://appsto.re/fr/HqzJQ.i)

**Comment by exycutez** [comment] 2017-02-20 08:25
I tried the OEBD-Facile app that was recomended above, took 2 secounds for it to find the dongle and it started blinking!

CanZE cant find it it seems, wierd? How long does it usually take for you guys for CanZE to find the dongle (first time)?

**Comment by GertjanVB** [comment] 2017-02-20 08:38
This is a concept guide for installation, hope this is helpfull;
[CanZE iOS Download and installation guide.pdf](https://github.com/fesch/CanZE/files/786904/CanZE.iOS.Download.and.installation.guide.pdf)

**Comment by fesch** [comment] 2017-02-20 08:45
@GertjanVB : May I post this guide on the CanZE Site as well?

**Comment by GertjanVB** [comment] 2017-02-20 09:11
Sure, Frederic and Jeroen have viewed and commented this document yesterday evening. Jeroen is in the proces of getting it on your site. Don't know what the routing exactly is

**Comment by exycutez** [comment] 2017-02-20 09:21
Well, this is what i have been doing, except the router and dns part. Still not working..

I assume its one of two:
1. CanZE does not work on i7 plus
2. CanZE dows bot work with an obdii wifi dobgle without pw protection

**Comment by GertjanVB** [comment] 2017-02-20 09:26
Did you start form scratch? eg. flush data on CanZE, close CanZE, remove and forget the WifiODB network and connect again with the proper settings before starting CanZE.
My CanZE runs on a 4S, can't tell wether or not there are problems with a 7plus. They do use different iOS versions

**Comment by exycutez** [comment] 2017-02-20 09:29
I tried flushing, reinstalling, forgetting wifi and so on..
Waiting 15-20 minutes on the attempting to connect to socket.. now im out of ideas!

Maybe the developer can answer regarding if its working with a open network obdII?

**Comment by FredLeudon** [comment] 2017-02-20 10:49
Sorry if CanZE don't work well on iPhone 7.

I tested it on iPhone 4s, 5c and 6

I will test it with iPhone 7 on simulator to try to reproduce your problem. 

Regards

Frédéric RICHARD

**Comment by FredLeudon** [comment] 2017-02-20 11:00
I just launched a test on iPhone 7 Plus simulator and it worked perfectly. 

Could you please send screenshots from:

iPhone settings app / wifi and wifi details

CanZE settings tab

Regards 

Frédéric RICHARD

**Comment by exycutez** [comment] 2017-02-20 11:03
Thanks for your effort to help,
I will send you screenshots when i get to the car later today!

**Comment by exycutez** [comment] 2017-02-20 14:37
![img_1484](https://cloud.githubusercontent.com/assets/25868062/23129282/4fe27a6e-f782-11e6-8f69-d06855451781.PNG)
![img_1486](https://cloud.githubusercontent.com/assets/25868062/23129284/502ba6e4-f782-11e6-9e5c-c6911ba59a73.PNG)
![img_1487](https://cloud.githubusercontent.com/assets/25868062/23129285/50359172-f782-11e6-8389-8e75bc10f0b8.PNG)

**Comment by FredLeudon** [comment] 2017-02-20 14:47
Ok, it seems correct. 

Try to uncheck "safe driving mode" and say if it's working better please.

You can try to uncheck "automatic connexion" and after launching CanZE, tap to the "connect" button 

Normally, connexion is made in a couple of seconds. 

Frédéric RICHARD

**Comment by exycutez** [comment] 2017-02-20 17:40
Troed unchecking those two.. Im close to giving up :/

Wierd that it works so fast with the other app u suggested! Do you think its because its an open wifi with no password?

**Comment by FredLeudon** [comment] 2017-02-20 18:31
No, that not the reason why it doesn't work. 

Assume "debug log" is on.
 
On main screen, tap delete log files button 

Force CanZE to quit by double pressing home button and sliding CanZE up

Launch CanZE, wait a moment and go to main screen ant tap "send feedback"

Mail app will open with a new mail for me. 
Delete attached file data.fic witch I don't need, send. 

I hope I can see whit it's not working in log file. 

A new version of CanZE ave been sent today to apple. It's pending for verification.

Perhaps installing this new version will help (I upgraded développement software) to solve your problems. 

Frédéric RICHARD

**Comment by sordoneF** [comment] 2017-02-20 19:00
I have an iPhone7 (Model MN932ZD/A with iOS 10.2.1) and it works well with Canze build 1.0.15.7 and my Wifi dongle. It has them same settings and no password, connect takes ca. 2 seconds (after selecting wifi for OBD in Wifi settings)

**Comment by FredLeudon** [comment] 2017-02-20 19:40
Ok, if CanZE works with iPhone 7, perhaps is it the dongle the program can't talk to?

Would you agree to send me your dongle, so I can test it and eventually (if possible) upgrade CanZE code to fit with your dongle?

Frédéric RICHARD

**Comment by GertjanVB** [comment] 2017-02-20 20:40
I thought It's the same dongle I send you earlier, you tested it and it was OK. May be a different version, this one doesn't have a make or modelnumber. Exycutez, can you confirm?
![img_3270](https://cloud.githubusercontent.com/assets/18355712/23140971/bc166222-f7b4-11e6-938d-f07de54c4dc8.JPG)

**Comment by FredLeudon** [comment] 2017-02-20 20:42
Sorry but I don't remember ;-)

Frédéric RICHARD

**Comment by fesch** [comment] 2017-02-20 21:19
Looks exactly like the one I have too, which is working ... 
I will test tomorrow with the latest version.

**Comment by GertjanVB** [comment] 2017-02-20 21:23
@FredLeudon : never mind ;-)  it was early september last year. I bought the dongle here http://www.ebay.nl/itm/ELM327-Wifi-Interface-Diagnostique-Auto-ODB2-Detecteur-Panne-iPhone-Android-/222020430447?hash=item33b172ea6f:g:OBsAAOxy6MBSRGBq

**Comment by yoh-there** [comment] 2017-02-20 21:24
Please be aware these are VERY generic dongle cases, including the labeling. Inside, these can be vastly different.

**Comment by exycutez** [comment] 2017-02-20 21:39
I can send you the dongle, but i am waiting for another one that arrives this week! Will try that one before sending it to you, since i eill recieve the new one before you get the one i have now!

Sending you feedback file now!

**Comment by FredLeudon** [comment] 2017-02-23 03:30
I didn't see anything in log files. 

The best way is to wait for your new dongle. 

If it works with new dongle, could you send the old one to me?

**Comment by exycutez** [comment] 2017-02-23 07:37
Allright, i will send you the old one if the new one is working.

Actually, i got 2 that is the same as my current one arriving verry soon, and a kw902 wifi that arrives abit later.. The Konwei kw902 should atleast work?

**Comment by exycutez** [comment] 2017-02-23 18:40
Secound dongle arrived (have one more of the same as we have spoken about, and one kw902 arriving also), and tested it with the new version of Canze.

This is what im getting now, it says the same after 5 minutes.
![img_1520](https://cloud.githubusercontent.com/assets/25868062/23273542/bd9032de-f9ff-11e6-9b0b-f528198bb48e.PNG)

So, is this normal? Now it doesnt even try to connect to the dongle it seems?

**Comment by FredLeudon** [comment] 2017-02-23 20:34
Hi, normally a couple of seconds. 

There is something wrong but I'm not sure that it is due to CanZE.

Can you again send screenshots of wifi settings and CanZE settings. 

For testing, assure you are using dhcp in iPhone's wifi settings.

Is your dongle recognized by eodb facile ?

If yes, go to "calculateurs", "console" and type ATZ and "envoyer" and send a screenshot.

Frédéric RICHARD

**Comment by FredLeudon** [comment] 2017-03-08 09:23
any news ?

**Comment by exycutez** [comment] 2017-03-08 10:13
Tried 3 different dongles, like the one i have linked to.. no one is working..
It seems like they dont work with OEBD-Facile either, so my previous answer with it working with OEBD-Facile (the app you recomended for testing) is not correct. In OEBD-Facile, all the dongles have the led's blinking, but it is not connecting.

Seems like the dongles are a cheap/fake obd ii? Now i am waiting for a kw902 wifi dongle to arrive (should arrove in some days). If that is not working, i would ask for any of you, that have a dobgle that works, to send me a link to one that is working?

**Comment by yoh-there** [comment] 2017-03-08 12:04
I propose to close this issue. Sorry if this sounds "Dutch", but we've put warnings about dongles and which ones work all over the website and several fora. We have no stake in the KONNWEI's, but it's the **only** one we know it works without too many problems **and** that can be ordered with limited risk of getting a non-working knock-off. Yes, we do see other successful dongles, but always no-brand and the next one can (and often will) fail.

For my co-developers: harsh as it may sound, my unasked-for advise is to not put any effort in it. It is a sinkhole of precious time and energy.

For the issuers: get a KONNWEI. If it fails, feel free to report.

**Comment by exycutez** [comment] 2017-03-08 12:18
Yeah, that is all fine by me.
I read somewere that any 1.5 wifi dongle worked, and i have seen pictures of other users dongle, so i thought it would work!
I am now waiting for the kw902, so lets hope it will works!

Thanks

**Closed as completed** 2019-01-06 12:48 UTC
Labels: question, iOS
