### ISSUE TITLE
Screen charging - Battery kilometers is not always updated

### ISSUE THREAD

**Issue by Albino-Zoe** [fesch/CanZE#435] opened 2017-02-15 13:30 UTC
Hi,
I already notice in V1.21 the value "battery kilometers is not always updated.
Excuse me for not telling it earlier, I was a little busy :-(
In V1.22 the same.
My test scenario:
At the beginning of the drive I start CanZE.
I switch between all screens and make a screenshot.
Then I decide for one screen and begin my drive.
At the finisch I switch again all screens and make screenshots.
In the screen "Charging" all values are correct, only "battery kilometers" still has the value from the start of the car trip
Do you need logging or screenshots ?

**Comment by yoh-there** [comment] 2017-02-15 13:37
No screenshots needed. I will use your routine and see if I can reproduce it.

**Comment by yoh-there** [comment] 2017-02-16 15:16
I am closing this issue. It seems by design (not mine, but Renaults). I drove for a bit and the battery km indeed stayed static. When I had locked the car the current odo km was transferred to the battery computer.

**Closed as completed by yoh-there** 2017-02-16 15:16 UTC

**Comment by Albino-Zoe** [comment] 2019-02-07 13:24
Closed is accepted ;-)

**Comment by yoh-there** [comment] 2019-02-09 22:43
Thank you sir
