### ISSUE TITLE
Character set/font is too big?

### ISSUE THREAD

**Issue by Albino-Zoe** [fesch/CanZE#527] opened 2019-02-07 14:09 UTC
In V1.29 are suddenly in different screen different font sizes!
Is that a problem that I can solve on the smartphone (SM-G930F; Android 9.0.0) or has something gone wrong here?
![screenshot_20190206-121008_canze_v1_29_klimaanlage](https://user-images.githubusercontent.com/25500628/52416604-4469a980-2aea-11e9-9aa0-dd92c51a4f92.jpg)
![screenshot_20190206-120721_canze_v_1_29_batterie](https://user-images.githubusercontent.com/25500628/52416605-4469a980-2aea-11e9-9e75-0d6568b43c11.jpg)
![screenshot_20190206-120805_canze_v_1_29_verbrauch](https://user-images.githubusercontent.com/25500628/52416606-45024000-2aea-11e9-8cee-f18185d2a195.jpg)

**Comment by fesch** [comment] 2019-02-07 14:24
I changed the fixed size font to some pdi-related untis.
The problem is, that some screen are meant to be looked at in landscape, while others are more for portrait usage. So this is why some of the text is to long. Please rotate your phone ;)

**Comment by yoh-there** [comment] 2019-02-09 22:03
@fesch are the properties of the widgets, at least the ones in the layout xmls, programatically changeable and would the widgets play nice with that? If so, would that be an option? TBH, I myself run the consumption screen almost always and in portrait. It would be kind of nice if this could be faciliated if it is not crazy much work

**Comment by fesch** [comment] 2019-02-10 08:17
Orientation can be detected, so a simple if statement should make the trick to make a difference between portrait and landscape...

**Comment by fesch** [comment] 2019-02-10 13:50
Fixed in the latest release.
Feel free to re-open if you think the font in portrait mode is still too big!

**Closed as completed by fesch** 2019-02-10 13:50 UTC
