### ISSUE TITLE
Charts: Color of description the same as color of line

### ISSUE THREAD

**Issue by HarmOtten** [fesch/CanZE#452] opened 2017-03-07 19:56 UTC
CanZE Android version.
Is it possible to make the color of the description of a line in the chart, the same as the line color?
This would make it much easier to read the charts.
This applies to the Climate screen, and Charging graphs screen.

**Comment by fesch** [comment] 2017-03-07 20:04
Should be. The problem is, that actually the text is being written within a single line of code. I'll check this ...

**Comment by fesch** [comment] 2017-03-07 20:06
... and is configured as a single line in the views config :(

**Comment by yoh-there** [comment] 2017-03-07 20:10
Comma separated, like the SIDs? Or is that too complex to position nicely, as they become separate entities?

**Comment by fesch** [comment] 2017-03-07 20:19
Must use that ... because the slash is no option --> km/h  :(

**Comment by fesch** [comment] 2017-03-07 20:26
Fixed in dev branche

**Closed as completed by fesch** 2017-03-07 20:26 UTC
Labels: enhancement, Android
