### ISSUE TITLE
TPMS ID read fails

### ISSUE THREAD

**Issue by minibiti** [fesch/CanZE#564] opened 2019-06-03 14:50 UTC
Hi,

I do not know if this has been reported in another issue but I can not read the TPMS IDs anymore. I just get 00000 with some error message.
This used to work so I am not sure what is wrong...

Can anyone else confirm the problem?

**Comment by yoh-there** [comment] 2019-06-03 21:17
Working on it. Duplicate of #554 so closing this one.

**Closed as completed by yoh-there** 2019-06-03 21:17 UTC
Labels: duplicate
