### ISSUE TITLE
immediate crash at tap on "Battery" - "Cell Voltages" 

### ISSUE THREAD

**Issue by jragg** [fesch/CanZE#251] opened 2015-12-07 21:07 UTC
immediate crash when tapping "Battery" - "Cell Voltages" 
Canze V1.07
Android 4.4.4
RedMi Note 4G

**Comment by fesch** [comment] 2015-12-07 21:45
Could you enable the "debug loggin" in the settings, restart CanZE, reproduce the crash and then send us the latest log file contained on the SD-card in the "canze" folder?

**Comment by jragg** [comment] 2015-12-07 21:55
No Bluetooth Connection, i am not in car, i am in a warmer place ;-)
but same failure here like in the car ...

Here are the last two files:
[2015-12-07-22-50-30.log.txt](https://github.com/fesch/CanZE/files/54611/2015-12-07-22-50-30.log.txt)
[2015-12-07-22-50-12.log.txt](https://github.com/fesch/CanZE/files/54612/2015-12-07-22-50-12.log.txt)

**Comment by fesch** [comment] 2015-12-07 22:05
Seams like there occurs a NullPointerException because an empty field is being called:

2015-12-07 22:50:25.408: !!! >> Field with following SID <> not found!

What car do you have selected in the settings?

**Comment by jragg** [comment] 2015-12-07 22:06
Car is ZOE in Settings and in real ;-)
Thanks!

**Comment by yoh-there** [comment] 2015-12-07 22:32
Same problem here. If I open "Battery", the widgets show, but as I tap on them, things crash. No definite pattern yet.

**Comment by fesch** [comment] 2015-12-08 05:52
Ahhh .. when double tapping on it. I now finally can confirm and reproduce...

Will take a look at it.

**Comment by fesch** [comment] 2015-12-08 15:10
@yoh-there: please check if the latest commit also works for you, so we could close this issue too ...

**Comment by yoh-there** [comment] 2015-12-08 15:31
No crashes :-)

**Closed as completed by yoh-there** 2015-12-08 15:31 UTC
